services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project.settings
      - key: DEBUG
        value: "False"
